__title__ = 'kote'
__description__ = 'Invisible Messaging'
__url__ = 'https://github.com/l-n-s/kote'
__version__ = '1.1'
__author__ = 'Viktor Villainov'
__author_email__ = 'supervillain@riseup.net'
__license__ = 'MIT'
__copyright__ = 'Copyright 2019 Viktor Villainov'
